# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secretflow_serving/protos/feature.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'secretflow_serving/protos/feature.proto\x12\x12secretflow.serving\"v\n\x0c\x46\x65\x61tureValue\x12\x12\n\x04i32s\x18\x01 \x03(\x05R\x04i32s\x12\x12\n\x04i64s\x18\x02 \x03(\x03R\x04i64s\x12\x0e\n\x02\x66s\x18\x03 \x03(\x02R\x02\x66s\x12\x0e\n\x02\x64s\x18\x04 \x03(\x01R\x02\x64s\x12\x0e\n\x02ss\x18\x05 \x03(\tR\x02ss\x12\x0e\n\x02\x62s\x18\x06 \x03(\x08R\x02\x62s\"U\n\x0c\x46\x65\x61tureField\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x31\n\x04type\x18\x02 \x01(\x0e\x32\x1d.secretflow.serving.FieldTypeR\x04type\"y\n\x07\x46\x65\x61ture\x12\x36\n\x05\x66ield\x18\x01 \x01(\x0b\x32 .secretflow.serving.FeatureFieldR\x05\x66ield\x12\x36\n\x05value\x18\x02 \x01(\x0b\x32 .secretflow.serving.FeatureValueR\x05value\"T\n\x0c\x46\x65\x61tureParam\x12\x1f\n\x0bquery_datas\x18\x01 \x03(\tR\nqueryDatas\x12#\n\rquery_context\x18\x02 \x01(\tR\x0cqueryContext*\x8a\x01\n\tFieldType\x12\x16\n\x12UNKNOWN_FIELD_TYPE\x10\x00\x12\x0e\n\nFIELD_BOOL\x10\x01\x12\x0f\n\x0b\x46IELD_INT32\x10\x02\x12\x0f\n\x0b\x46IELD_INT64\x10\x03\x12\x0f\n\x0b\x46IELD_FLOAT\x10\x04\x12\x10\n\x0c\x46IELD_DOUBLE\x10\x05\x12\x10\n\x0c\x46IELD_STRING\x10\x06\x62\x06proto3')

_FIELDTYPE = DESCRIPTOR.enum_types_by_name['FieldType']
FieldType = enum_type_wrapper.EnumTypeWrapper(_FIELDTYPE)
UNKNOWN_FIELD_TYPE = 0
FIELD_BOOL = 1
FIELD_INT32 = 2
FIELD_INT64 = 3
FIELD_FLOAT = 4
FIELD_DOUBLE = 5
FIELD_STRING = 6


_FEATUREVALUE = DESCRIPTOR.message_types_by_name['FeatureValue']
_FEATUREFIELD = DESCRIPTOR.message_types_by_name['FeatureField']
_FEATURE = DESCRIPTOR.message_types_by_name['Feature']
_FEATUREPARAM = DESCRIPTOR.message_types_by_name['FeatureParam']
FeatureValue = _reflection.GeneratedProtocolMessageType('FeatureValue', (_message.Message,), {
  'DESCRIPTOR' : _FEATUREVALUE,
  '__module__' : 'secretflow_serving.protos.feature_pb2'
  # @@protoc_insertion_point(class_scope:secretflow.serving.FeatureValue)
  })
_sym_db.RegisterMessage(FeatureValue)

FeatureField = _reflection.GeneratedProtocolMessageType('FeatureField', (_message.Message,), {
  'DESCRIPTOR' : _FEATUREFIELD,
  '__module__' : 'secretflow_serving.protos.feature_pb2'
  # @@protoc_insertion_point(class_scope:secretflow.serving.FeatureField)
  })
_sym_db.RegisterMessage(FeatureField)

Feature = _reflection.GeneratedProtocolMessageType('Feature', (_message.Message,), {
  'DESCRIPTOR' : _FEATURE,
  '__module__' : 'secretflow_serving.protos.feature_pb2'
  # @@protoc_insertion_point(class_scope:secretflow.serving.Feature)
  })
_sym_db.RegisterMessage(Feature)

FeatureParam = _reflection.GeneratedProtocolMessageType('FeatureParam', (_message.Message,), {
  'DESCRIPTOR' : _FEATUREPARAM,
  '__module__' : 'secretflow_serving.protos.feature_pb2'
  # @@protoc_insertion_point(class_scope:secretflow.serving.FeatureParam)
  })
_sym_db.RegisterMessage(FeatureParam)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FIELDTYPE._serialized_start=480
  _FIELDTYPE._serialized_end=618
  _FEATUREVALUE._serialized_start=63
  _FEATUREVALUE._serialized_end=181
  _FEATUREFIELD._serialized_start=183
  _FEATUREFIELD._serialized_end=268
  _FEATURE._serialized_start=270
  _FEATURE._serialized_end=391
  _FEATUREPARAM._serialized_start=393
  _FEATUREPARAM._serialized_end=477
# @@protoc_insertion_point(module_scope)
