__title__ = "arthub_api"
__description__ = "ArHhub Python SDK"
__url__ = ""
__version__ = "1.8.14"
__author__ = "Joey Ding"
__author_email__ = "joeyding@tencent.com"
__license__ = "Apache 2.0"
__copyright__ = "Copyright 2022 Tencent"
