# Generated by Django 4.2.11 on 2024-03-24 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoryProfile',
        ),
    ]
