# Generated by Django 4.2.11 on 2024-03-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_delete_historyprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('first_name', models.CharField(max_length=32, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=32, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('is_identified', models.DateTimeField(null=True, verbose_name='Идентифицирован')),
                ('is_verified', models.DateTimeField(null=True, verbose_name='Верифицирован')),
                ('is_sign', models.DateTimeField(help_text='Получена подпись при личном контакте', null=True, verbose_name='Личная подпись')),
                ('passport_serial', models.CharField(max_length=4, verbose_name='Серия')),
                ('passport_number', models.CharField(max_length=6, verbose_name='Номер')),
                ('passport_birth_place', models.CharField(blank=True, max_length=256, verbose_name='Место рождения')),
                ('passport_issue_name', models.CharField(blank=True, max_length=256, verbose_name='Кем выдан')),
                ('passport_code', models.CharField(max_length=16, verbose_name='Код паспорта')),
                ('passport_date', models.DateField(verbose_name='Дата выдачи')),
                ('snils', models.CharField(max_length=64, null=True, verbose_name='Снилс')),
                ('postal_code', models.CharField(blank=True, max_length=16, verbose_name='Индекс')),
                ('state', models.CharField(blank=True, max_length=256, verbose_name='Регион')),
                ('city', models.CharField(blank=True, max_length=256, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=256, verbose_name='Улица')),
                ('house', models.CharField(blank=True, max_length=8, verbose_name='Дом')),
                ('apt', models.CharField(blank=True, max_length=8, verbose_name='Кв')),
                ('income', models.PositiveIntegerField(blank=True, help_text='Ежемесячный доход', null=True, verbose_name='Доход')),
                ('user_id', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'История изменений',
                'verbose_name_plural': 'История изменений',
            },
        ),
    ]
