#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2402-25-gd44eb56d"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2402
#define NETGEN_VERSION_TWEAK 25
#define NETGEN_VERSION_HASH "gd44eb56d"
#endif // NETGEN_VERSION_HPP_INCLUDED
