# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.29
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr

class StorageV1TokenRequest(BaseModel):
    """
    TokenRequest contains parameters of a service account token.  # noqa: E501
    """
    audience: StrictStr = Field(..., description="audience is the intended audience of the token in \"TokenRequestSpec\". It will default to the audiences of kube apiserver.")
    expiration_seconds: Optional[StrictInt] = Field(default=None, alias="expirationSeconds", description="expirationSeconds is the duration of validity of the token in \"TokenRequestSpec\". It has the same default value of \"ExpirationSeconds\" in \"TokenRequestSpec\".")
    __properties = ["audience", "expirationSeconds"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> StorageV1TokenRequest:
        """Create an instance of StorageV1TokenRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> StorageV1TokenRequest:
        """Create an instance of StorageV1TokenRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return StorageV1TokenRequest.parse_obj(obj)

        _obj = StorageV1TokenRequest.parse_obj({
            "audience": obj.get("audience"),
            "expiration_seconds": obj.get("expirationSeconds")
        })
        return _obj


