# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.29
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr

class V1GRPCAction(BaseModel):
    """
    V1GRPCAction
    """
    port: StrictInt = Field(..., description="Port number of the gRPC service. Number must be in the range 1 to 65535.")
    service: Optional[StrictStr] = Field(default=None, description="Service is the name of the service to place in the gRPC HealthCheckRequest (see https://github.com/grpc/grpc/blob/master/doc/health-checking.md).  If this is not specified, the default behavior is defined by gRPC.")
    __properties = ["port", "service"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> V1GRPCAction:
        """Create an instance of V1GRPCAction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> V1GRPCAction:
        """Create an instance of V1GRPCAction from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return V1GRPCAction.parse_obj(obj)

        _obj = V1GRPCAction.parse_obj({
            "port": obj.get("port"),
            "service": obj.get("service")
        })
        return _obj


