# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.29
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr

class V1IngressClassParametersReference(BaseModel):
    """
    IngressClassParametersReference identifies an API object. This can be used to specify a cluster or namespace-scoped resource.  # noqa: E501
    """
    api_group: Optional[StrictStr] = Field(default=None, alias="apiGroup", description="apiGroup is the group for the resource being referenced. If APIGroup is not specified, the specified Kind must be in the core API group. For any other third-party types, APIGroup is required.")
    kind: StrictStr = Field(..., description="kind is the type of resource being referenced.")
    name: StrictStr = Field(..., description="name is the name of resource being referenced.")
    namespace: Optional[StrictStr] = Field(default=None, description="namespace is the namespace of the resource being referenced. This field is required when scope is set to \"Namespace\" and must be unset when scope is set to \"Cluster\".")
    scope: Optional[StrictStr] = Field(default=None, description="scope represents if this refers to a cluster or namespace scoped resource. This may be set to \"Cluster\" (default) or \"Namespace\".")
    __properties = ["apiGroup", "kind", "name", "namespace", "scope"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> V1IngressClassParametersReference:
        """Create an instance of V1IngressClassParametersReference from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> V1IngressClassParametersReference:
        """Create an instance of V1IngressClassParametersReference from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return V1IngressClassParametersReference.parse_obj(obj)

        _obj = V1IngressClassParametersReference.parse_obj({
            "api_group": obj.get("apiGroup"),
            "kind": obj.get("kind"),
            "name": obj.get("name"),
            "namespace": obj.get("namespace"),
            "scope": obj.get("scope")
        })
        return _obj


