# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.29
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr

class V1ObjectFieldSelector(BaseModel):
    """
    ObjectFieldSelector selects an APIVersioned field of an object.  # noqa: E501
    """
    api_version: Optional[StrictStr] = Field(default=None, alias="apiVersion", description="Version of the schema the FieldPath is written in terms of, defaults to \"v1\".")
    field_path: StrictStr = Field(..., alias="fieldPath", description="Path of the field to select in the specified API version.")
    __properties = ["apiVersion", "fieldPath"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> V1ObjectFieldSelector:
        """Create an instance of V1ObjectFieldSelector from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> V1ObjectFieldSelector:
        """Create an instance of V1ObjectFieldSelector from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return V1ObjectFieldSelector.parse_obj(obj)

        _obj = V1ObjectFieldSelector.parse_obj({
            "api_version": obj.get("apiVersion"),
            "field_path": obj.get("fieldPath")
        })
        return _obj


