# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.29
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr

class V1beta1ExpressionWarning(BaseModel):
    """
    ExpressionWarning is a warning information that targets a specific expression.  # noqa: E501
    """
    field_ref: StrictStr = Field(..., alias="fieldRef", description="The path to the field that refers the expression. For example, the reference to the expression of the first item of validations is \"spec.validations[0].expression\"")
    warning: StrictStr = Field(..., description="The content of type checking information in a human-readable form. Each line of the warning contains the type that the expression is checked against, followed by the type check error from the compiler.")
    __properties = ["fieldRef", "warning"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> V1beta1ExpressionWarning:
        """Create an instance of V1beta1ExpressionWarning from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> V1beta1ExpressionWarning:
        """Create an instance of V1beta1ExpressionWarning from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return V1beta1ExpressionWarning.parse_obj(obj)

        _obj = V1beta1ExpressionWarning.parse_obj({
            "field_ref": obj.get("fieldRef"),
            "warning": obj.get("warning")
        })
        return _obj


