# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.29
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field
from .v2_metric_identifier import V2MetricIdentifier
from .v2_metric_target import V2MetricTarget

class V2ExternalMetricSource(BaseModel):
    """
    ExternalMetricSource indicates how to scale on a metric not associated with any Kubernetes object (for example length of queue in cloud messaging service, or QPS from loadbalancer running outside of cluster).  # noqa: E501
    """
    metric: V2MetricIdentifier = Field(...)
    target: V2MetricTarget = Field(...)
    __properties = ["metric", "target"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> V2ExternalMetricSource:
        """Create an instance of V2ExternalMetricSource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of metric
        if self.metric:
            _dict['metric'] = self.metric.to_dict()
        # override the default output from pydantic by calling `to_dict()` of target
        if self.target:
            _dict['target'] = self.target.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> V2ExternalMetricSource:
        """Create an instance of V2ExternalMetricSource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return V2ExternalMetricSource.parse_obj(obj)

        _obj = V2ExternalMetricSource.parse_obj({
            "metric": V2MetricIdentifier.from_dict(obj.get("metric")) if obj.get("metric") is not None else None,
            "target": V2MetricTarget.from_dict(obj.get("target")) if obj.get("target") is not None else None
        })
        return _obj


