
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-25T15:52:42+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0a21c6aaecae0b51fe3b8d97f4906101abc1ffc8",
 "version": "1.7.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
