#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2402-24-gf96ccabe"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2402
#define NETGEN_VERSION_TWEAK 24
#define NETGEN_VERSION_HASH "gf96ccabe"
#endif // NETGEN_VERSION_HPP_INCLUDED
