
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-25T12:30:07+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "4710e9b08fcefcde3538ca7be3fe1285a2a48792",
 "version": "1.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
