from enum import Enum


class JobType(Enum):
    """
    꿀맛 일괄 작업 종류
    """
    # 행안부 데이터 처리 작업


    # 데이터

    #
    # 가게 데이터 수집 작업
    #
    UPDATE_STORE_PERMIT_DATA = 'PREPARE_SEARCHING_KEYWORDS'
    PREPARE_STORE_SEARCHING_KEYWORDS = 'PREPARE_STORE_SEARCHING_KEYWORDS'
    SEARCH_STORE_IN_NAVERPLACE_BY_KEYWORD = 'SEARCH_STORE_IN_NAVERPLACE_BY_KEYWORD'
    MATCH_STORE_TO_SEARCHED_RESULT_BY_KEYWORD = 'SEARCH_STORE_IN_NAVERPLACE_BY_KEYWORD'
    GET_STORE_DETAIL_IN_NAVERPLACE = 'GET_STORE_DETAIL_IN_NAVERPLACE'

    # 좌표기반 가게 데이터 수집 작업
    CREATE_SEARCH_STORE_TASK_IN_ROI_RANGE = 'CREATE_SEARCH_STORE_TASK_IN_ROI_RANGE'
    GET_STORE_DETAIL_IN_ROI_FROM_NAVERPLACE = 'GET_STORE_DETAIL_IN_ROI_FROM_NAVERPLACE'



    # 정규화 작업
    NORMALIZE_NAVER_STORE = 'NORMALIZE_NAVER_STORE'
    NORMALIZE_NAVER_STORE_REVIEW = 'NORMALIZE_NAVER_STORE_REVIEW'
    NORMALIZE_YOUTUBE = 'NORMALIZE_YOUTUBE'
    NORMALIZE_NAVER_BLOG = 'NORMALIZE_NAVER_BLOG'
    NORMALIZE_INSTAGRAM = 'NORMALIZE_INSTAGRAM'

    # PK NaverplaceiD
    NORMALIZE_NAVER_STORE_USING_NAVERPLACE_ID = 'NORMALIZE_NAVER_STORE_USING_NAVERPLACE_ID'




    # 네이버에서 가게 검색 작업
    PREPARE_SEARCHING_KEYWORDS = 'PREPARE_SEARCHING_KEYWORDS'
    SEARCH_KEYWORD = 'SEARCH_KEYWORD'
    SEARCH_STORE_BY_ADDRESS = 'SEARCH_STORE_BY_ADDRESS'
    SEARCH_STORE_IN_NAVERPLACE_BY_NAVERPLACE_NAME = 'SEARCH_STORE_IN_NAVERPLACE_BY_NAVERPLACE_NAME'
    # 네이버 데이터 수집 작업
    GET_STORE_VISITOR_REVIEW_IN_NAVERPLACE = 'GET_STORE_VISITOR_REVIEW_IN_NAVERPLACE'
    GET_STORE_BLOG_REVIEW_RELATED_BY_STORE_IN_NAVERPLACE = 'GET_STORE_BLOG_REVIEW_IN_NAVERPLACE'
    GET_STORE_NAVER_REVIEW_RELATED_BY_STORE_IN_NAVERPLACE = 'GET_STORE_DETAIL_IN_NAVERPLACE'

    #PK NaverplaceID
    GET_STORE_BLOG_REVIEW_RELATED_BY_STORE_IN_NAVERPLACE_USING_NAVERPLACE_ID = 'GET_STORE_BLOG_REVIEW_IN_NAVERPLACE_USING_NAVERPLACE_ID'
    GET_STORE_NAVER_REVIEW_RELATED_BY_STORE_IN_NAVERPLACE_USING_NAVERPLACE_ID = 'GET_STORE_DETAIL_IN_NAVERPLACE_USING_NAVERPLACE_ID'


    # Youtube 데이터 수집 작업
    SEARCH_YOUTUBE_POST_BY_KEYWORD = 'SEARCH_YOUTUBE_POST_BY_KEYWORD'
    SEARCH_YOUTUBE_POST_RELATED_BY_STORE_IN_YOUTUBE = 'SEARCH_YOUTUBE_POST_RELATED_BY_STORE_IN_YOUTUBE'
    SEARCH_BLOG_POST_RELATED_BY_STORE = 'SEARCH_BLOG_POST_RELATED_BY_STORE'
    SEARCH_NAVER_REVIEW_POST_RELATED_BY_STORE = 'SEARCH_NAVER_REVIEW_POST_RELATED_BY_STORE'

    #PK NaverplaceID
    SEARCH_YOUTUBE_POST_RELATED_BY_STORE_IN_YOUTUBE_USING_NAVERPLACE_ID = 'SEARCH_YOUTUBE_POST_RELATED_BY_STORE_IN_YOUTUBE_USING_NAVERPLACE_ID'
    SEARCH_YOUTUBE_POST_RELATED_BY_STORE_IN_YOUTUBE_USING_NAVERPLACE_ID_USING_UNOFFICIAL_API = 'SEARCH_YOUTUBE_POST_RELATED_BY_STORE_IN_YOUTUBE_USING_NAVERPLACE_ID_USING_UNOFFICIAL_API'
    # Instagram 데이터 수집 작업









