
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-28T18:00:08-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "adbdc84276a0b631932ec55a32030d65c86e88c1",
 "version": "2.16.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
