class BaseError(Exception): ...

class InvalidVersionError(BaseError): ...
class InvalidVersionPartError(InvalidVersionError): ...
class FixPartNotSupported(InvalidVersionError): ...

class NotComparableError(BaseError): ...

class DecreaseVersionError(BaseError): ...