# Generated by Django 3.1.5 on 2021-01-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitbituser',
            name='fitbit_id',
            field=models.IntegerField(null=True),
        ),
    ]
