
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-24T17:54:06+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "73548fd23039ebfcce119dbed0077b38fb3bf8a5",
 "version": "0.0.2.dev"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
