{"metadata":{"kernelspec":{"name":"python3","display_name":"Python 3 (ipykernel)","language":"python"},"language_info":{"name":"python","version":"3.12.2","mimetype":"text/x-python","codemirror_mode":{"name":"ipython","version":3},"pygments_lexer":"ipython3","nbconvert_exporter":"python","file_extension":".py"}},"nbformat_minor":5,"nbformat":4,"cells":[{"id":"b0ff27bb-79db-4eb3-aa8c-4668263e631a","cell_type":"code","source":"from vpython import *\nscene = canvas() # This is needed in Jupyter notebook and lab to make programs easily rerunnable\n# Kadir Haldenbilen, February 2011\n# Converted to Web VPython by Bruce Sherwood, May 2022\n\nscene.width = 1024\nscene.height = 768\nscene.center = vec(-2,0,0)\nscene.range = 7\n\nmotor = []      # elements that rotate\ncl = 2\nns = 24\n\ndef makearc(center=[0,0], radius=1, angle1=2*pi-pi/4, angle2=2*pi+pi/4, ccw=True):\n    # Specify angle1 and angle2 as positive numbers, with angle2 > angle1\n    if angle2 < angle1:\n        raise Exception(\"Both angles must be positive, with angle2 > angle1\") \n    n = 20\n    dtheta = abs(angle2-angle1)/n\n    ret = []\n    for i in range(n+1):\n        if ccw:\n            #print(center, angle1, angle2, radius, ccw)\n            ret.append([center[0]+radius*cos(angle1+i*dtheta), center[1]+radius*sin(angle1+i*dtheta)])\n        else:\n            #print(center, angle1, angle2, radius, ccw)\n            ret.append([center[0]+radius*cos(angle2-i*dtheta), center[1]+radius*sin(angle2-i*dtheta)])\n    return ret\n\ndef rotatepoints(points=[[1,0],[0,1]], angle=0, origin=vec(0,0,0)):\n    s = sphere(visible=False)\n    ret = []\n    for p in points:\n        s.pos = vec(p[0],p[1],0)\n        s.rotate(angle=angle, axis=vec(0,0,1), origin=origin)\n        ret.append([s.pos.x,s.pos.y])\n    return ret \n\n#=====================================================================\n# Create contactor\n\np2 = makearc(center=[0,0], radius=0.5, angle1=0, angle2=pi/20, ccw=False)\np1 = makearc(center=[0,0], radius=1.2, angle1=0, angle2=pi/15, ccw=True)\np = p1+p2+[p1[0]]\nc = extrusion(path=[vec(0,0,0),vec(2,0,0)], shape=p, color=vec(1,0.5,0.3))\ncont = [c]\nfor i in range(1,24):\n    con = c.clone()\n    con.rotate(angle=i*2*pi/24, axis=vec(-1,0,0), origin=vec(0,0,0))\n    cont.append(con)\nmotor.append(compound(cont))\n#==========================================================================\n# Create contactor soldering tips\n\np1 = makearc(center=[0,0], radius=1.4, angle1=2*pi-0.5*pi/24, angle2=2*pi+0.4*pi/24, ccw=True)\np2 = makearc(center=[0,0], radius=0.7, angle1=2*pi-0.5*pi/30, angle2=2*pi+0.4*pi/30, ccw=False)\np = p1+p2+[p1[0]]\nc = extrusion(path=[vec(-0.4,0,0),vec(0,0,0)], shape=p, color=vec(1,0.5,0.3))\ns = sphere(pos=vec(-0.2,0,1.195), radius=0.1, shininess=1)\ncont = [c]\nballs = []\nfor i in range(23):\n    con = c.clone()\n    con.rotate(angle=(i+1)*2*pi/24, axis=vec(1,0,0), origin=vec(0,0,0))\n    cont.append(con)\n    con = s.clone()\n    con.rotate(angle=(i+1)*2*pi/24, axis=vec(1,0,0), origin=vec(0,0,0))\n    balls.append(con)\n    \nmotor.append(compound(cont))\nmotor.append(compound(balls))\n#=========================================================================\n# Add shaft insulator material\n# Define a circular ring of thickness=0.05\nsc = shapes.circle(radius=0.53, thickness=0.05)\n# Extrude the ring to get a thin hollow cylinder insulator over the shaft\nsce = extrusion(path=[vec(-7,0,0),vec(2.5,0,0)], shape=sc, color=vec(0.8,0,0),\n                emissive=True) # plastic\n\n# The Rotor Shaft, defined by a simple cylinder\nshaft = cylinder(pos=vec(3.5,0,0), axis=vec(-11.25,0,0), radius=0.495, color=color.gray(.6), texture=textures.metal)\n\n# Add a piece of gear at one end of the shaft\n# Use the gear shape to define the shape, note radius, addendum, dedendum sizes\ngr = shapes.gear(n=9, radius=0.455, addendum=0.04, dedendum=0.06, fradius=0.01)\n# Extrude the gear shape appending it to the shaft end\ngre = extrusion(path=[vec(3.5,0,0),vec(5,0,0)], shape=gr, color=color.gray(.6),\n                texture=textures.metal)\n\nmotor.append(gre)\n#for o in scene.objects: o.visible = False\n#==========================================================================\n# Define Rotor Core\n# Normally the core should have been built of many very thin sheets\n# For performance reasons, a single block is built\n# First define the outer circle\n\nr0 = 0.495  # radius of shaft\nr1 = 1.3    # radius of disk\nr2 = 2.7  # radius of inner portion of top of the T\nr3 = 3 # radius of outer portion of top of the T\ntheta = pi/12 # angle between Ts\nd = 0.25*theta # half angle width of upright of T\ndlt = 0.05\nthk = 5.04\n\np1 = makearc(center=[0,0], radius=r1, angle1=2*pi-pi/12+d, angle2=2*pi+pi/12-d, ccw=True)\nstart = r1*vec(cos(-pi/12+d), sin(-pi/12+d),0)\n# From middle of bottom of T base to middle of top of T upright:\nmiddledir = vec(cos(pi/12),sin(pi/12), 0)\nperp = middledir.rotate(angle=pi/2, axis=vec(0,0,1))\np1end = vec(p1[-1][0], p1[-1][1],0)\nendpt1 = p1end+(r2-r1)*middledir # top right of T upright\nnextstart = start.rotate(angle=pi/6, axis=vec(0,0,1))\nendpt2 = nextstart + (r2-r1)*middledir\na = atan(endpt1.y/endpt1.x)\np2 = makearc(center=[0,0], radius=r2, angle1=0.3*a, angle2=a, ccw=False)\np1.extend(p2)\np3 = makearc(center=[0,0], radius=r3, angle1=0.3*a, angle2=1.5*a+2*d, ccw=True)\np1.extend(p3)\nb = atan(endpt2.y/endpt2.x)\np4 = makearc(center=[0,0], radius=r2, angle1=b, angle2=1.5*a+2*d, ccw=False)\np1.extend(p4)\n\npc = p1.copy()\nfor i in range(1,12):\n    p = rotatepoints(p1, angle=i*pi/6)\n    pc.extend(p)\npc.append(pc[0])\n\nex = extrusion(path=[vec(-6,0,0), vec(-6+thk,0,0)], shape=[pc, shapes.circle(radius=r0)] , color=color.gray(0.7))\nmotor.append(ex)\n\n#==========================================================================\n# Do the core wire windings\nx = -3.5\nn = 20\nL = 1.3\nthk = L/50\ncon = []\nfor i in range(n):\n    r = r1+i*thk*2.5\n    inner = shapes.rectangle(width=5.2, height=.35, roundness=0.4)\n    outer = shapes.rectangle(width=5.3+i*0.7/n, height=0.4+i*0.6/n, roundness=0.4)\n    p = [vec(x,r*sin(pi/12),r*cos(pi/12)), vec(x,(r+thk)*sin(pi/12),(r+thk)*cos(pi/12))]\n    ex = extrusion(path=p, shape=[outer,inner], color=vec(.7,.5,.15))\n    con.append(ex)\nex = compound(con)\ncon = [ex]\n\nfor i in range(1,12):\n    c = ex.clone()\n    c.rotate(angle=i*pi/6, axis=vec(1,0,0), origin=vec(0,0,0))\n    con.append(c)\n\nmotor.append(compound(con))\n\n#==========================================================================\n# Connect contactor surfaces to windings with cables\npos = vec(-1.3,1.1,0)\nc0 = cylinder(pos=pos, axis=vec(-0.25,1.2,0.25)-pos, radius=0.05, color=color.blue)\ncon = [c0]\nfor i in range(1,24):\n    c = c0.clone()\n    c.rotate(angle=i*pi/6, axis=vec(1,0,0), origin=vec(c0.pos.x,0,0))\n    con.append(c)\nmotor.append(compound(con))\n\n#==========================================================================\n# Create Brushes\n# From a rectangular cross section, subtract rotor contactor circle, leaving us two\n# brushes on each sides of the contactor, with circular profile\n#br = shapes.rectangle(width=5, height=0.4)\nbr = makearc(center=[0,0], radius=1.21, angle1=2*pi-atan(0.2/1.21), angle2=2*pi+atan(0.2/1.21), ccw=True)\nd = 1+1.21*cos(atan(.2/1.21))\nbr.append([d,0.2])\nbr.append([d,-0.2])\nbr.append(br[0])\nbre = extrusion(path=[vec(0.4,0,0),vec(1.6,0,0)], color=vec(0.1,0.1,0.15),\n                texture=textures.rough, shape=br)\nd = bre.clone()\nd.rotate(angle=pi, axis=vec(1,0,0), origin=vec(1,0,0))\n\n#==========================================================================\n# Create Brush Housings\n# Define a rectangular frame, with a thickness of 0.1\nbh = shapes.rectangle(width=1.3, height=0.5, thickness=0.1)\n# Extrude the rectangular frame to obtain hollow boxes for each housing\nbhe1 = extrusion(path=[vec(1,0,1.4),vec(1,0,2.9)], shape=bh, color=vec(0.9,1,0.8),\n                 texture=textures.rough)\nbhe2 = extrusion(path=[vec(1,0,-1.4),vec(1,0,-2.9)], shape=bh, color=vec(0.9,1,0.8),\n                 texture=textures.rough)\n\n#==========================================================================\n# Place a screw on each housing to fix the power cables\n# Create a screw head profile by subtracting a cross from a circle\nscrh = [shapes.circle(radius=0.15)]\nscrh.append(shapes.cross(width=0.2, thickness=0.04))\n# Extrude a little to get the screw head\nscrhw1path = [vec(1,0.2,2.7),vec(1,0.3,2.7)]\nscrhw2path = [vec(1,0.2,-2.7),vec(1,0.3,-2.7)]\nscrhw1 = extrusion(path=scrhw1path, shape=scrh, texture=textures.metal)\nscrhw2 = extrusion(path=scrhw2path, shape=scrh, texture=textures.metal)\n\n#==========================================================================\n# Create the screw bodies\n# Use a square to create the body with teeth\nscrb = shapes.rectangle(scale=0.05)\nyi = .2\nyf = -.3\ndy = (yi-yf)/20\npts = []\nfor i in range(20):\n    pts.append(vec(1, yi-i*dy, 2.7))\n# Extrude the square with twist parameter to get the teeth of the screw\n# It appears that paths.line() is broken.\n#scrbe1 = extrusion(path=paths.line(start=vec(2.7,0.2,1), end=vec(2.7,-0.3,1),\nscrbe1 = extrusion(path=pts, shape=scrb, twist=0.4, color=vec(1,1,0.9),\n                 texture=textures.rough)\n\npts = []\nfor i in range(20):\n    pts.append(vec(1, yi-i*dy, -2.7))\nscrbe2 = extrusion(path=pts, shape=scrb, twist=0.4, color=vec(1,1,0.9),\n                 texture=textures.rough)\n\n#==========================================================================\n\ncrdl = [ [2.8,-0.2], [2.8,-1.6], [-2.8,-1.6], [-2.8,-0.2] ] # ccw\na = acos(0.2/1.1) # starting angle for near half-circle\nc = makearc(center=[0,0], radius=1.25, angle1=1.5*pi-a, angle2=1.5*pi+a, ccw=True)\ncrdl.extend(c)\ncrdl.append(crdl[0])\ncrdl = [crdl, shapes.circle(pos=[-2.2,-0.9], radius=0.1)]\ncrdle = extrusion(path=[vec(1.8,-0.05,0),vec(0.2,-0.05,0)], shape=crdl,\n            color=0.7*color.white, emissive=True)\n\n#==========================================================================\n# Connect power cables to the brushes\n# Use simple curves to define cables\ncol = vec(1,0.5,0.3)\ncbl1i = curve(pos=[scrhw1path[0], scrhw1path[0]- vec(0,0,-2)],\n            radius=0.03, color=col)\ncbl1o = curve(pos=[scrhw1path[0], scrhw1path[0]- vec(0,0,-1.5)],\n            radius=0.05, color=vec(0,0,1))\ncb12ipos = [scrhw2path[0], scrhw2path[0], scrhw2path[0]+vec(0,0,-0.5), \n            scrhw2path[0]+vec(0,0,-0.5)+vec(0,-2,0),\n            scrhw2path[0]+vec(0,0,-0.5)+vec(0,-2,0)+vec(0,0,7)]\ncbl2i = curve(pos=cb12ipos, radius=0.03, color=col)\n\n#==========================================================================\n# Add ball-bearings at both ends of the shaft\nbra = shapes.circle(radius=0.6, thickness=0.2)\nbrb = shapes.circle(radius=1.1, thickness=0.2)\nbr1 = extrusion(path=[vec(2.5,0,0), vec(3.25,0,0)], shape=bra, color=color.gray(.7))\nbr1 = extrusion(path=[vec(2.5,0,0), vec(3.25,0,0)], shape=brb, color=color.gray(.7))\nbr2 = extrusion(path=[vec(-7,0,0), vec(-7.75,0,0)], shape=bra, color=color.gray(.7),\n    shininess=1, texture=textures.metal)\nbr2 = extrusion(path=[vec(-7,0,0), vec(-7.75,0,0)], shape=brb, color=color.gray(.7),\n    shininess=1, texture=textures.metal)\n\n#==========================================================================\n# Do not forget to add the balls\nbbrs1 = []\nbbrs2 = []\nfor i in range(7):\n    ex1 = sphere(pos=vec(3, 0.75*cos(i*2*pi/7.0), 0.75*sin(i*2*pi/7.0)),\n                        radius=0.25)\n    bbrs1.append(ex1)\n    \n    ex2 = sphere(pos=vec(-7.375, 0.75*cos(i*2*pi/7.0), 0.75*sin(i*2*pi/7.0)),\n                        radius=0.25)\n    bbrs2.append(ex2)\nmotor.append(compound(bbrs1, texture=textures.rough))\nmotor.append(compound(bbrs2, texture=textures.rough))\n\n#==========================================================================\n# Here is a complex path definition for stator winding, which is not planar.\n# The path is made up of an arc in YZ + line in ZX + arc in ZY + line in XZ\npp = paths.arc(angle1=-pi/3.5, angle2=pi/3.5, radius=3.4)\nfor p in pp:\n    p.y = -p.x\n    p.x = -1\ntt = []\nfor p in pp:\n    tt.append(vec(-6,p.y,p.z))\ntt.reverse()\npp.extend(tt)\npp.append(pp[0])\nextrusion(path=pp, shape=shapes.circle(radius=0.3), color=color.red)\n    \n#==========================================================================\n# Make stator base:\n# We did not include all stator parts here for better visualisation\n# Use a rounded rectangle for the stator base.\n# Subtract a large circle in the middle to allow for the rotor\n# Subtract circular holes to place the stator windings\n# Subtract some more holes for fixing the stator core on the motor body\n\n#def makearc(center=[0,0], radius=1, angle1=2*pi-pi/4, angle2=2*pi+pi/4, ccw=True):\n    # Specify angle1 and angle2 as positive numbers, with angle2 > angle1\np1 = makearc(center=[1.5,0], radius=1.5, angle1=3*pi/2, angle2=2*pi, ccw=True)\np2 = makearc(center=[2.7,0.22], radius=0.3, angle1=pi+pi/4, angle2=2*pi-pi/4, ccw=False)\np3 = makearc(center=[0,2.1], radius=3.1, angle1=pi+0.95*pi/4, angle2=2*pi-0.95*pi/4, ccw=False)\np4 = makearc(center=[-2.7,0.22], radius=0.3, angle1=pi+pi/4, angle2=2*pi-pi/4, ccw=False)\np5 = makearc(center=[-1.5,0], radius=1.5, angle1=pi, angle2=1.5*pi, ccw=True)\n\np1.extend(p2)\np1.extend(p3)\np1.extend(p4)\np1.extend(p5)\np1.append(p1[0])\n\nh1 = shapes.circle(pos=[2,-1.07], radius=0.15)\nh2 = shapes.circle(pos=[-2,-1.07], radius=0.15)\n\nextrusion(path=[vec(-6,-2.3,0), vec(-1,-2.3,0)], shape=[p1,h1,h2])\n\n#==========================================================================\n# Create the motor cover as a rotational extrusion along the mootor\n# Add two rounded rectangles which will cover all the rotor and stator.\n# Leave the tips of shaft outside the cover\nL = 11\nr = 2\nR = 5\nt = 0.25\nx = 3*t\ns = [ [-L/2, -r/2-t], [-L/2,-r/2], [-L/2+x,-r/2], [-L/2+x,R/2], [L/2-x,R/2], [L/2-x,-r/2], [L/2,-r/2],\n     [L/2,-r/2-t], [L/2-x-t,-r/2-t], [L/2-x-t,R/2-t], [-L/2+x+t,R/2-t], \n     [-L/2+x+t,-r/2-t], [-L/2+t,-r/2-t], [-L/2,-r/2-t] ]\n\np = paths.arc(radius=R/2, angle1=0, angle2=pi+pi/4)\nex = extrusion(path=p, shape=s, color=0.6*color.green, up=vec(1,0,0), texture=textures.rough)\nex.rotate(angle=pi/2, axis=vec(0,0,1))\nex.pos = vec(-2.2,0,-0.65)\n\nrun = True\ndef running(b):\n    global run\n    if b.text == 'Run': b.text = 'Pause'\n    else: b.text = 'Run'\n    run = not run\n    \nbutton(text='Pause', bind=running)\n\nscene.append_to_caption(\"\"\"\\nTo rotate \"camera\", drag with right button or Ctrl-drag.\nTo zoom, drag with middle button or Alt/Option depressed, or use scroll wheel.\n  On a two-button mouse, middle is left + right.\nTo pan left/right and up/down, Shift-drag.\nTouch screen: pinch/extend to zoom, swipe or two-finger rotate.\"\"\")\n\n# Connect power cables\nangl = pi/400\n# Turn on the motor\nwhile True:\n    rate(100)\n    if run:\n        for o in motor:\n            o.rotate(angle=angl, axis=vec(-1,0,0))\n            \n\n            ","metadata":{"trusted":false},"outputs":[{"data":{"text/plain":"<IPython.core.display.HTML object>","text/html":"<div id=\"glowscript\" class=\"glowscript\"></div>"},"metadata":{},"output_type":"display_data"},{"metadata":{},"data":{"text/plain":"<IPython.core.display.Javascript object>","application/javascript":"if (typeof Jupyter !== \"undefined\") { window.__context = { glowscript_container: $(\"#glowscript\").removeAttr(\"id\")};}else{ element.textContent = ' ';}"},"output_type":"display_data"},{"output_type":"display_data","data":{"text/html":"<div id=\"glowscript\" class=\"glowscript\"></div>","text/plain":"<IPython.core.display.HTML object>"},"metadata":{}},{"metadata":{},"output_type":"display_data","data":{"application/javascript":"if (typeof Jupyter !== \"undefined\") { window.__context = { glowscript_container: $(\"#glowscript\").removeAttr(\"id\")};}else{ element.textContent = ' ';}","text/plain":"<IPython.core.display.Javascript object>"}}],"execution_count":null},{"id":"e329e81d-2c60-4e49-ae5b-f0fa19add348","cell_type":"code","source":"","metadata":{"trusted":false},"outputs":[],"execution_count":null}]}