
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-26T03:15:02+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "52195bbba97196b1fd930df4bc7c5def16ab0a90",
 "version": "1.1.31"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
