## Size definitions
_MM_TO_INCH = 0.0393700787

SIZE_SM = 30 * _MM_TO_INCH
SIZE_10 = 90 * _MM_TO_INCH
SIZE_15 = 140 * _MM_TO_INCH
SIZE_20 = 190 * _MM_TO_INCH

# Papers (Science, Nature)
# Width
PAPER_CW = 90 * _MM_TO_INCH
PAPER_FW = 190 * _MM_TO_INCH
# Height
PAPER_DH = PAPER_CW / 1.618
PAPER_GH = PAPER_CW / 1.618

# 16:9 slides
# Width
SLIDE_FW = 10
SLIDE_HW = SLIDE_FW / 2
SLIDE_TW = SLIDE_FW / 3
SLIDE_TTW = SLIDE_FW * 2 / 3
SLIDE_FTW = SLIDE_FW * 5 / 12
# Height
SLIDE_FH = SLIDE_FW * 9 / 16
SLIDE_HH = SLIDE_FH / 2
SLIDE_TH = SLIDE_FH / 3
SLIDE_TTH = SLIDE_FH * 2 / 3
SLIDE_FTH = SLIDE_FH * 5 / 12

# A0 poster
# Height
POSTER_FH = 46.8
POSTER_HH = POSTER_FH / 2
POSTER_TH = POSTER_FH / 3
POSTER_QH = POSTER_FH / 4
POSTER_RH = POSTER_FH / 5
POSTER_SH = POSTER_FH / 6
# Width
POSTER_FW = 33.1
POSTER_HW = POSTER_FW / 2
POSTER_TW = POSTER_FW / 3
POSTER_QW = POSTER_FW / 4
POSTER_RW = POSTER_FW / 5
POSTER_SW = POSTER_FW / 6
