from .webshell import Webshell
from .utils import get_behinder4_jsp_shell
from .utils import get_behinder4_php_shell
from .utils import get_behinder4_aspx_shell
from .utils import get_behinder3_aspx_shell
from .utils import get_godzilla_jsp_shell
from .utils import get_godzilla_jspx_shell
from .utils import get_godzilla_php_shell
from .utils import get_godzilla_aspx_shell
from .utils import get_godzilla_ashx_shell
from .utils import get_define_class_shell
from .utils import get_shell_result
