
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-28T01:33:08+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "52b556c4082a1f18376d8a97c8ab3ca5b25cc949",
 "version": "0.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
