# coding: utf-8

"""
    Robust Intelligence REST API

    API methods for Robust Intelligence. Users must authenticate using the `rime-api-key` header.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: dev@robustintelligence.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GenerativefirewallPiiEntityType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    UNSPECIFIED = "PII_ENTITY_TYPE_UNSPECIFIED"
    ABA_ROUTING_NUMBER = "PII_ENTITY_TYPE_ABA_ROUTING_NUMBER"
    AU_ABN = "PII_ENTITY_TYPE_AU_ABN"
    AU_ACN = "PII_ENTITY_TYPE_AU_ACN"
    AU_MEDICARE_NUMBER = "PII_ENTITY_TYPE_AU_MEDICARE_NUMBER"
    AU_TFN = "PII_ENTITY_TYPE_AU_TFN"
    CREDIT_CARD_NUMBER = "PII_ENTITY_TYPE_CREDIT_CARD_NUMBER"
    EMAIL = "PII_ENTITY_TYPE_EMAIL"
    IBAN_CODE = "PII_ENTITY_TYPE_IBAN_CODE"
    IP_ADDRESS = "PII_ENTITY_TYPE_IP_ADDRESS"
    MEDICAL_LICENSE_NUMBER = "PII_ENTITY_TYPE_MEDICAL_LICENSE_NUMBER"
    PHONE_NUMBER = "PII_ENTITY_TYPE_PHONE_NUMBER"
    NHS_NUMBER = "PII_ENTITY_TYPE_NHS_NUMBER"
    US_BANK_NUMBER = "PII_ENTITY_TYPE_US_BANK_NUMBER"
    US_DRIVERS_LICENSE_NUMBER = "PII_ENTITY_TYPE_US_DRIVERS_LICENSE_NUMBER"
    US_ITIN = "PII_ENTITY_TYPE_US_ITIN"
    US_PASSPORT_NUMBER = "PII_ENTITY_TYPE_US_PASSPORT_NUMBER"
    US_SSN = "PII_ENTITY_TYPE_US_SSN"
    AZURE_DOCUMENT_DB_AUTH_KEY = "PII_ENTITY_TYPE_AZURE_DOCUMENT_DB_AUTH_KEY"
    AZURE_PUBLISH_SETTING_PASSWORD = "PII_ENTITY_TYPE_AZURE_PUBLISH_SETTING_PASSWORD"
    AZURE_STORAGE_ACCOUNT_KEY = "PII_ENTITY_TYPE_AZURE_STORAGE_ACCOUNT_KEY"
    EU_NATIONAL_IDENTIFICATION_NUMBER = "PII_ENTITY_TYPE_EU_NATIONAL_IDENTIFICATION_NUMBER"
    EU_SSN = "PII_ENTITY_TYPE_EU_SSN"
    EU_TAX_IDENTIFICATION_NUMBER = "PII_ENTITY_TYPE_EU_TAX_IDENTIFICATION_NUMBER"
    EU_DRIVERS_LICENSE_NUMBER = "PII_ENTITY_TYPE_EU_DRIVERS_LICENSE_NUMBER"
    EU_PASSPORT_NUMBER = "PII_ENTITY_TYPE_EU_PASSPORT_NUMBER"
    INTERNATIONAL_BANKING_ACCOUNT_NUMBER = "PII_ENTITY_TYPE_INTERNATIONAL_BANKING_ACCOUNT_NUMBER"
    UK_ELECTORAL_ROLL_NUMBER = "PII_ENTITY_TYPE_UK_ELECTORAL_ROLL_NUMBER"
    UK_NATIONAL_HEALTH_NUMBER = "PII_ENTITY_TYPE_UK_NATIONAL_HEALTH_NUMBER"
    UK_NATIONAL_INSURANCE_NUMBER = "PII_ENTITY_TYPE_UK_NATIONAL_INSURANCE_NUMBER"
    UK_UNIQUE_TAXPAYER_NUMBER = "PII_ENTITY_TYPE_UK_UNIQUE_TAXPAYER_NUMBER"
    UK_DRIVERS_LICENSE_NUMBER = "PII_ENTITY_TYPE_UK_DRIVERS_LICENSE_NUMBER"
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
    }

    attribute_map = {
    }

    def __init__(self):  # noqa: E501
        """GenerativefirewallPiiEntityType - a model defined in Swagger"""  # noqa: E501
        self.discriminator = None

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GenerativefirewallPiiEntityType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GenerativefirewallPiiEntityType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
