from .cd_irregular import CDIrregular
from .channel_cos_flow import ChannelCosFlow
from .convection_3d import Convection3D
from .diffusion_3d import Diffusion3D
from .fracture_thermal_flow import FractureThermalFlow
from .fracture_flow_1d import FractureFlow1D
from .gaussian_hill_2d import GaussianHill2D
from .gaussian_hill_3d import GaussianHill3D
from .poiseuille_flow import PoiseuilleFlow
from .reinjection_1d import Reinjection1D
from .reinjection_2d import Reinjection2D
from .semi_infinite_flow_1d import SemiInfiniteFlow1D
from .theis import Theis
from .uniform_flow import UniformFlow
