# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secretflow_serving/protos/data_type.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)secretflow_serving/protos/data_type.proto\x12\x12secretflow.serving*\xd9\x01\n\x08\x44\x61taType\x12\x13\n\x0fUNKNOWN_DT_TYPE\x10\x00\x12\x0b\n\x07\x44T_BOOL\x10\x01\x12\x0c\n\x08\x44T_UINT8\x10\x02\x12\x0b\n\x07\x44T_INT8\x10\x03\x12\r\n\tDT_UINT16\x10\x04\x12\x0c\n\x08\x44T_INT16\x10\x05\x12\r\n\tDT_UINT32\x10\x06\x12\x0c\n\x08\x44T_INT32\x10\x07\x12\r\n\tDT_UINT64\x10\x08\x12\x0c\n\x08\x44T_INT64\x10\t\x12\x0c\n\x08\x44T_FLOAT\x10\x0b\x12\r\n\tDT_DOUBLE\x10\x0c\x12\r\n\tDT_STRING\x10\r\x12\r\n\tDT_BINARY\x10\x0e\x62\x06proto3')

_DATATYPE = DESCRIPTOR.enum_types_by_name['DataType']
DataType = enum_type_wrapper.EnumTypeWrapper(_DATATYPE)
UNKNOWN_DT_TYPE = 0
DT_BOOL = 1
DT_UINT8 = 2
DT_INT8 = 3
DT_UINT16 = 4
DT_INT16 = 5
DT_UINT32 = 6
DT_INT32 = 7
DT_UINT64 = 8
DT_INT64 = 9
DT_FLOAT = 11
DT_DOUBLE = 12
DT_STRING = 13
DT_BINARY = 14


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATATYPE._serialized_start=66
  _DATATYPE._serialized_end=283
# @@protoc_insertion_point(module_scope)
