if __name__ == 'ld.test.str_util_test':
    from ..common import Logger
    from ..common.StrUtil import StrUtil, 文本
    print('日志')
    log = Logger.get_framework_logger()
    s = StrUtil.remove_whitespace(' 123 ')
    s = StrUtil.remove_leading_whitespace(' 123 ')
    s = StrUtil.remove_leading_whitespace(' 123 ')
    s = StrUtil.remove_trailing_whitespace(' 123 ')
    s = StrUtil.remove_all_whitespace(' 123 ')
    s = StrUtil.custom_split(' 123 23', '2')
    s = StrUtil.extract_letters('23零动学院2KK22aseD')
    s = StrUtil.extract_chinese_characters('23 零动学院    2KK22aseD')
    s = StrUtil.extract_numbers('23 零动学院    2KK22aseD')
    s = StrUtil.replace_text('23 零动学院    2KK22aseD', '零动', '仙乐')
    s = StrUtil.generate_random_chinese(2)
    s = StrUtil.generate_random_lowercase(5)
    s = StrUtil.generate_random_uppercase(5)
    s = StrUtil.generate_random_mixed(5)
    s = 文本.随机生成大写字母(5)
    s = 文本.随机生成小写字母(5)
    s = 文本.随机生成混合字符(5)
    s = 文本.随机生成汉字(5)
    s = 文本.分割('123', '2')
    s = 文本.提取字母('23零动学院2KK22aseD')
    s = 文本.删除全部空格(' 23零动学院2KK22 ase D ')
    s = 文本.删除头部空格(' 23零动学院2KK22 ase D ')
    s = 文本.删除尾部空格(' 23零动学院2KK22 ase D ')
    s = 文本.提取字母(' 23零动学院2KK22 ase D ')
    s = 文本.提取数字(' 23零动学院2KK22 ase D ')
    s = 文本.提取汉字(' 23零动学院2KK22 ase D ')
    s = 文本.替换文本('23 零动学院    2KK22aseD', '零动', '仙乐')
    s = 文本.随机生成数字(5)