
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-25T21:46:53+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "66e6e96d4f04cad3d8e67b966a82f5cc8bdeb8f0",
 "version": "1.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
