# coding: utf-8

"""
    JSONmode

    Turn data and any schema into clean JSON via LLM API

    The version of the OpenAPI document: alpha
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.define_api import DefineApi


class TestDefineApi(unittest.TestCase):
    """DefineApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefineApi()

    def tearDown(self) -> None:
        pass

    def test_define_prompt_parts_define_post(self) -> None:
        """Test case for define_prompt_parts_define_post

        Define Prompt Parts
        """
        pass


if __name__ == '__main__':
    unittest.main()
