
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-03-28T13:40:28-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "0b25ec4eb72cf2d3a0f8e14e9fa34833ea3a65db",
 "version": "5.4.28"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
