
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-19T15:24:35+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "fcddad2474444c44f3c9fedd0cd92738092b2751",
 "version": "0.14.0+189.gfcddad2474"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
