# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fundamentum_edge_proto/telemetry.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&fundamentum_edge_proto/telemetry.proto\x12\x17\x63om.fundamentum.edge.v1\x1a\x1bgoogle/protobuf/empty.proto\"n\n\x10TelemetryRequest\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\x11\n\tsub_topic\x18\x02 \x01(\t\x12.\n\x03qos\x18\x03 \x01(\x0e\x32\x1c.com.fundamentum.edge.v1.QosH\x00\x88\x01\x01\x42\x06\n\x04_qos*H\n\x03Qos\x12\x14\n\x10QOS_AT_MOST_ONCE\x10\x00\x12\x15\n\x11QOS_AT_LEAST_ONCE\x10\x01\x12\x14\n\x10QOS_EXACTLY_ONCE\x10\x02\x32[\n\tTelemetry\x12N\n\x07Publish\x12).com.fundamentum.edge.v1.TelemetryRequest\x1a\x16.google.protobuf.Empty(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fundamentum_edge_proto.telemetry_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_QOS']._serialized_start=208
  _globals['_QOS']._serialized_end=280
  _globals['_TELEMETRYREQUEST']._serialized_start=96
  _globals['_TELEMETRYREQUEST']._serialized_end=206
  _globals['_TELEMETRY']._serialized_start=282
  _globals['_TELEMETRY']._serialized_end=373
# @@protoc_insertion_point(module_scope)
