__title__ = 'boldqc'
__description__ = 'BOLD QC'
__url__ = 'https://github.com/harvard-nrg/boldqc'
__version__ = '0.4.1'
__author__ = 'Neuroinformatics Research Group'
__author_email__ = 'info@neuroinfo.org'
