
class TwitterCrawler:
    def __init__(self):...
    def retweet(self):...
    def follow(self): ...
    def like(self): ...
    def quote(self): ...
    def comment(self): ...

class MediumCrawler:
    def __init__(self): ...
    def clap(self): ...
    def follow(self): ...
    def comment(self): ...


class DiscordCrawler:
    def __init__(self): ...
    def channel(self, channel): ...
    def getUsername(self): ...
    
class TelegramCrawler:
    def __init__(self): ...
    def channel(self, channel): ...
    def getUsername(self): ...

class FacebookCrawler:
    def __init__(self): ...
