# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from terrascope_api.models import system_pb2 as system__pb2


class SystemApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_ping = channel.unary_unary(
                '/oi.papi.SystemApi/get_ping',
                request_serializer=system__pb2.PingRequest.SerializeToString,
                response_deserializer=system__pb2.PingResponse.FromString,
                )


class SystemApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_ping(self, request, context):
        """*
        Represents the ping endpoint. Use this to do a quick availability check for the service.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SystemApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_ping': grpc.unary_unary_rpc_method_handler(
                    servicer.get_ping,
                    request_deserializer=system__pb2.PingRequest.FromString,
                    response_serializer=system__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'oi.papi.SystemApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SystemApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/oi.papi.SystemApi/get_ping',
            system__pb2.PingRequest.SerializeToString,
            system__pb2.PingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
