# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.29
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field, StrictInt

class CoreV1EventSeries(BaseModel):
    """
    EventSeries contain information on series of events, i.e. thing that was/is happening continuously for some time.  # noqa: E501
    """
    count: Optional[StrictInt] = Field(default=None, description="Number of occurrences in this series up to the last heartbeat time")
    last_observed_time: Optional[datetime] = Field(default=None, alias="lastObservedTime", description="Time of the last occurrence observed")
    __properties = ["count", "lastObservedTime"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CoreV1EventSeries:
        """Create an instance of CoreV1EventSeries from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CoreV1EventSeries:
        """Create an instance of CoreV1EventSeries from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CoreV1EventSeries.parse_obj(obj)

        _obj = CoreV1EventSeries.parse_obj({
            "count": obj.get("count"),
            "last_observed_time": obj.get("lastObservedTime")
        })
        return _obj


