# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.29
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist

class V1alpha2PodSchedulingContextSpec(BaseModel):
    """
    PodSchedulingContextSpec describes where resources for the Pod are needed.  # noqa: E501
    """
    potential_nodes: Optional[list[StrictStr]] = Field(default=None, alias="potentialNodes", description="PotentialNodes lists nodes where the Pod might be able to run.  The size of this field is limited to 128. This is large enough for many clusters. Larger clusters may need more attempts to find a node that suits all pending resources. This may get increased in the future, but not reduced.")
    selected_node: Optional[StrictStr] = Field(default=None, alias="selectedNode", description="SelectedNode is the node for which allocation of ResourceClaims that are referenced by the Pod and that use \"WaitForFirstConsumer\" allocation is to be attempted.")
    __properties = ["potentialNodes", "selectedNode"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> V1alpha2PodSchedulingContextSpec:
        """Create an instance of V1alpha2PodSchedulingContextSpec from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> V1alpha2PodSchedulingContextSpec:
        """Create an instance of V1alpha2PodSchedulingContextSpec from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return V1alpha2PodSchedulingContextSpec.parse_obj(obj)

        _obj = V1alpha2PodSchedulingContextSpec.parse_obj({
            "potential_nodes": obj.get("potentialNodes"),
            "selected_node": obj.get("selectedNode")
        })
        return _obj


