# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.29
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, conlist
from .v1beta1_expression_warning import V1beta1ExpressionWarning

class V1beta1TypeChecking(BaseModel):
    """
    TypeChecking contains results of type checking the expressions in the ValidatingAdmissionPolicy  # noqa: E501
    """
    expression_warnings: Optional[list[V1beta1ExpressionWarning]] = Field(default=None, alias="expressionWarnings", description="The type checking warnings for each expression.")
    __properties = ["expressionWarnings"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> V1beta1TypeChecking:
        """Create an instance of V1beta1TypeChecking from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in expression_warnings (list)
        _items = []
        if self.expression_warnings:
            for _item in self.expression_warnings:
                if _item:
                    _items.append(_item.to_dict())
            _dict['expressionWarnings'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> V1beta1TypeChecking:
        """Create an instance of V1beta1TypeChecking from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return V1beta1TypeChecking.parse_obj(obj)

        _obj = V1beta1TypeChecking.parse_obj({
            "expression_warnings": [V1beta1ExpressionWarning.from_dict(_item) for _item in obj.get("expressionWarnings")] if obj.get("expressionWarnings") is not None else None
        })
        return _obj


