from __future__ import annotations
from maix._maix import app
from maix._maix import camera
from maix._maix import comm
from maix._maix import display
from maix._maix import err
from maix._maix import example
from maix._maix import fs
from maix._maix import i18n
from maix._maix import image
from maix._maix import nn
from maix._maix import peripheral
from maix._maix.peripheral import adc
from maix._maix.peripheral import gpio
from maix._maix.peripheral import i2c
from maix._maix.peripheral import pwm
from maix._maix.peripheral import spi
from maix._maix.peripheral import timer
from maix._maix.peripheral import uart
from maix._maix.peripheral import wdt
from maix._maix import protocol
from maix._maix import tensor
from maix._maix import thread
from maix._maix import time
from maix._maix import touchscreen
import sys as sys
from . import _maix
from . import version
__all__ = ['adc', 'app', 'camera', 'comm', 'display', 'err', 'example', 'fs', 'gpio', 'i18n', 'i2c', 'image', 'nn', 'peripheral', 'protocol', 'pwm', 'spi', 'sys', 'tensor', 'thread', 'time', 'timer', 'touchscreen', 'uart', 'version', 'wdt']
__version__: str = '4.0.0'
